name = "RdJUFiles"
uuid = "46bd9b67-29e2-46b0-bb29-da07b42f7d11"
authors = ["Naoki Maeda <fnkyksj@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
